#!/usr/bin/env node
// Copies the browser libraries the Wrapped page inlines from devDependencies into src/vendor/.
// Run after bumping a devDependency: `node scripts/vendor-assets.js`. The output is committed so the
// published CLI keeps a single runtime dependency (commander) and the page works offline.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const NM = path.join(ROOT, 'node_modules');
const OUT = path.join(ROOT, 'src', 'vendor');

const FONT_WEIGHTS = [400, 600, 800];
const FONT_SUBSETS = ['latin', 'vietnamese'];
// Only the icons the page actually uses (meaningful markers, not decoration).
const ICONS = [
  'download', 'git-commit-horizontal', 'calendar-days', 'layers', 'clock', 'message-square-text',
  'rotate-ccw', 'pencil-line', 'square-terminal', 'file-search', 'cpu', 'folder-git-2', 'copy', 'check', 'link',
];

const read = (...p) => fs.readFileSync(path.join(NM, ...p), 'utf8');
const version = (pkg) => JSON.parse(read(pkg, 'package.json')).version;
const write = (rel, content) => {
  const file = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  console.log(`  ${path.relative(ROOT, file)} (${(Buffer.byteLength(content) / 1024).toFixed(1)} KB)`);
};

function vendorScripts() {
  // anime.js ships its own license header in the minified bundle.
  write('anime.umd.min.js', read('animejs', 'dist', 'bundles', 'anime.umd.min.js'));
  const h2i = read('html-to-image', 'dist', 'html-to-image.js').replace(/\n\/\/# sourceMappingURL=.*$/m, '');
  const copyright = read('html-to-image', 'LICENSE').split('\n').find((l) => l.startsWith('Copyright')).trim();
  write('html-to-image.min.js', `/*! html-to-image v${version('html-to-image')} | MIT License | ${copyright} */\n${h2i}`);
}

function vendorFonts() {
  const faces = [];
  for (const weight of FONT_WEIGHTS) {
    const css = read('@fontsource', 'be-vietnam-pro', `${weight}.css`);
    for (const subset of FONT_SUBSETS) {
      const file = `be-vietnam-pro-${subset}-${weight}-normal.woff2`;
      const block = css.split('@font-face').find((b) => b.includes(file));
      const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)[1].trim();
      fs.mkdirSync(path.join(OUT, 'fonts'), { recursive: true });
      fs.copyFileSync(path.join(NM, '@fontsource', 'be-vietnam-pro', 'files', file), path.join(OUT, 'fonts', file));
      faces.push({ file, weight, unicodeRange });
    }
  }
  write(path.join('fonts', 'font-faces.json'), `${JSON.stringify(faces, null, 2)}\n`);
}

function vendorIcons() {
  const entries = ICONS.map((name) => {
    const svg = read('lucide-static', 'icons', `${name}.svg`);
    const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'))
      .replace(/\s*\n\s*/g, '').replace(/\s*\/>/g, '/>');
    return `  '${name}': '${inner}',`;
  });
  write('lucide-icons.js', `// Lucide icons v${version('lucide-static')} (ISC License, Copyright (c) Lucide Icons and Contributors).
// Generated by scripts/vendor-assets.js: inner SVG markup only, wrapped by icon() at render time.
export const LUCIDE_ICONS = {
${entries.join('\n')}
};

/** Inline 24x24 stroke icon; decorative unless a label is passed. */
export function icon(name, { size = 20, label } = {}) {
  const a11y = label ? \`role="img" aria-label="\${label}"\` : 'aria-hidden="true"';
  return \`<svg class="ico" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" \${a11y}>\${LUCIDE_ICONS[name]}</svg>\`;
}
`);
}

function vendorLicenses() {
  const files = {
    'animejs.txt': ['animejs', 'LICENSE.md'],
    'html-to-image.txt': ['html-to-image', 'LICENSE'],
    'lucide.txt': ['lucide-static', 'LICENSE'],
    'be-vietnam-pro-ofl.txt': ['@fontsource', 'be-vietnam-pro', 'LICENSE'],
  };
  for (const [out, src] of Object.entries(files)) write(path.join('licenses', out), read(...src));
}

console.log('Vendoring Wrapped page assets into src/vendor/');
vendorScripts();
vendorFonts();
vendorIcons();
vendorLicenses();
